services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
